# Generated by Django 3.1.4 on 2021-01-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidator', '0002_auto_20210103_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
